(function(ThemeBuilder) {

    var PreviewViewModel = function(cssTemplateLoader, previewRepository, parentIframeNotifier) {

        var DYNAMIC_STYLES_ID = "dynamic-styles",
             _cssTemplateLoader = cssTemplateLoader,
             currentState = {
                 theme: {
                     name: null,
                     colorScheme: null
                 },
                 group: null
             };

        var makeReplacedValue = function(constName) {
            var str = constName.replace("@", "").replace(/_/g, "-").toLowerCase();
            str = str.replace("5-", "-five-");
            str = str.replace("6-", "-six-");
            str = str.replace("7-", "-seven-");
            str = str.replace("8-", "-eight-");
            return "dx-theme-builder-" + str + "(?=(\\s|;|,|}))";
        };

        var removeOverlaysFromBody = function() {
            $("body > .dx-overlay").remove();
        };

        this.typography = ko.observable();
        this.isMobileTheme = ko.observable(false);

        this.widgets = ko.observableArray();

        this._createCssFromTemplate = function(metadata, cssTemplate) {
            var css = cssTemplate;
            $.each(metadata, function(i, group) {
                for(var j = 0, len = group.length; j < len; j++) {
                    var key = makeReplacedValue(group[j].Key);
                    var regExp = new RegExp(key, "g");
                    css = css.replace(regExp, group[j].Value);
                }
            });

            return css;
        };

        this._createDynamicStyles = function(css) {
            $("#" + DYNAMIC_STYLES_ID).remove();

            $("<style>" + css + "</style>")
                .attr("type", "text/css")
                .attr("id", DYNAMIC_STYLES_ID)
                .appendTo("head");
        };

        this.applyInlineStyles = function(metadata, theme, colorScheme) {
            var d = $.Deferred(),
                that = this;
            _cssTemplateLoader.load(theme, colorScheme).done(function(cssTemplate) {
                var css = that._createCssFromTemplate(metadata, cssTemplate);
                that._createDynamicStyles(css);
                d.resolve();
            });

            return d.promise();
        };

        this.getCSS = function(metadataVersion) {
            var css = "/* Generated by the DevExpress Theme Builder v" + metadataVersion + " */";
            css += $("#" + DYNAMIC_STYLES_ID).html();
            parentIframeNotifier.notify("getCSS", css);
        };

        this.init = function(metadata, theme, colorScheme, group, clearBody) {
            var that = this,
                updateWidgetsPreview = false,
                previewData = previewRepository.getData({ name: theme, colorScheme: colorScheme }, group);

            this.typography("dx-theme-" + theme + "-typography");
            this.isMobileTheme($.inArray(theme, ["ios", "ios7", "android", "win8", "android5"]) > -1);

            if(currentState.theme.name !== theme || currentState.theme.colorScheme !== colorScheme || currentState.group !== group)
                updateWidgetsPreview = true;

            that.applyInlineStyles(metadata, theme, colorScheme).done(function() {
                if(clearBody)
                    removeOverlaysFromBody();
                
                if(updateWidgetsPreview || !that.widgets().length)
                    that.widgets(previewData);

                parentIframeNotifier.notify("stylesUpdated");

                currentState.theme.name = theme;
                currentState.theme.colorScheme = colorScheme;
                currentState.group = group;
            });
        };
    };

    ThemeBuilder.PreviewViewModel = PreviewViewModel;

})(ThemeBuilder);